Coalery: Complete of s2/week4
devouring-algorithm-ds/algorithm-study-s2 pull request #31
Opened 2021-06-06 17:30 UTC by Coalery

- 스택 구현
- 배열로 스택 구현
- LeetCode 문제 풀이

2021-06-07 09:54 UTC, ipflegen requested changes

2021-06-07 09:54 UTC, ipflegen commented on week4/coalery/implementation/stack.hpp
> +}
`26`번줄에서 아래와 같이 예외 케이스를 확인하는 조건이 아닌, 반대로 "올바른 값인 경우 OOO를 한다"로 한 이유가 있을까요?
```cpp
if(this-length <= 0) /* error */ 
```

2021-06-07 09:58 UTC, ipflegen approved these changes

2021-06-07 09:58 UTC, ipflegen commented on week4/coalery/1021.cpp
> +        }
저는 flag세우는 방식으로 접근했는데 이렇게 하면 간단했네요 :)

2021-06-07 09:59 UTC, Coalery commented on week4/coalery/implementation/stack.hpp
> +}
`head`에 대입하는 경우 `length` 가 0이든 1이든 해야하는거라서 저렇게 했어요!

2021-06-07 10:02 UTC, ipflegen approved these changes
좋아요 :) 수고하셨어요.

2021-06-07 10:07 UTC, ipflegen commented on week4/coalery/implementation/stack.hpp
> +}
조건문이 없어도 되겠네요.
```cpp
void Stack<T>::push(T data) {
    Node <T> *newNode = new Node<T>(data);
    newNode->next = this->head;
    this->head = newNode;
    this->length++;
}
```

2021-06-07 10:18 UTC, Coalery commented on week4/coalery/implementation/stack.hpp
> +}
아 헐 그러네요 세상에

2021-06-07 12:19 UTC, ipflegen commented on week4/coalery/20.cpp
> +        return true;
```cpp
return s.empty();
```

2021-06-07 12:48 UTC, ipflegen commented on week4/coalery/155.cpp
> +        int min = ((1 << 30) - 1) * 2 + 1; // Prevent Overflow
```cpp
#include <climits>.. // something like that

int min = INT_MAX; // INT64_MAX;

// https://en.cppreference.com/w/cpp/types/integer
// https://www.cplusplus.com/reference/climits/
```

2021-06-08 13:23 UTC, ipflegen commented
@Coalery 리뷰 확인 완료 후, 머지 부탁 드립니다.

2021-06-08 13:53 UTC, merged